"use strict";

// Source excerpts and outputs are authored fiction, never retrieved institutional data.
(() => {
  const source = (name, location, excerpt) => ({ name, location, excerpt });
  const output = (heading, text, cites = []) => ({ heading, text, cites });
  function scenario(id, title, task, instructions, words, tags, sources, freeOutput, premiumOutput, friction, enablers, handoff) {
    const constraints = `Under ${words} words. Don't invent anything; mark missing or conflicting evidence [TO CONFIRM]. Use no names, IDs, or personal records. This is a draft for human review, not an approval.`;
    return {
      id, title, task, tags, sources, freeOutput, premiumOutput, friction, enablers, handoff,
      freePrompt: `${instructions}\n\nUse only the material I provide below. I will locate the current versions, check that they may be shared here, and remove personal or restricted information before pasting. Distinguish source facts from your recommendations. If a source is absent, do not infer its contents.\n\n${sources.map(s => `${s.name}:\n[paste your data here: approved, non-identifying excerpts from ${s.location}]`).join("\n\n")}\n\n${constraints}`,
      premiumPrompt: `${instructions}\n\nUse ${sources.map(s => `"${s.name}" in ${s.location}`).join("; ")}. Cite the supporting sources; if you cannot access one, say so.\n\n${constraints}`
    };
  }
  window.SHOWCASE_ROLES = [
    {
      id: "registrar", name: "Registrar / Student Records", shortName: "Registrar", icon: "RE",
      description: "Policy-grounded answers without turning student records into prompt material.",
      prompts: [
        scenario(1, "Explain an enrollment hold", "Turn a policy and an operational update into a clear next step for students.",
          "Draft a student-facing explanation of an administrative enrollment hold: what it means, how to resolve it, where to get help, and when to expect an update. Do not promise removal or describe an individual case.", 180, ["enrollment", "holds", "policy"],
          [source("Enrollment Hold Policy", "Registrar SharePoint", "Administrative document holds are reviewed by Student Records after the required documentation is received. A hold is not removed by an advising appointment."),
           source("Registration Readiness Recap", "Tuesday's Registrar Teams meeting", "The team requested a single explanation for administrative document holds. The revised review turnaround is pending approval; do not publish the prior target."),
           source("Student Service Directory", "Student Services SharePoint", "Student Records handles document questions through the authenticated service portal. Advising helps with course planning, not document-hold clearance.")],
          [output("What this means", "An administrative hold may affect registration. The reason and applicable policy need to be checked [TO CONFIRM]."),
           output("Your next step", "Review the hold notice and provide the requested documents through the approved channel [TO CONFIRM]."),
           output("When to expect an update", "The responsible office and review timeframe have not been supplied [TO CONFIRM]. This draft cannot determine whether your hold can be removed.")],
          [output("What this means", "An administrative document hold requires Student Records review after the requested documentation is received; an advising appointment alone does not clear it.", [1]),
           output("Your next step", "Use the authenticated service portal for document questions. Advising can help with course planning but does not clear document holds.", [3]),
           output("When to expect an update", "The revised turnaround is awaiting approval [TO CONFIRM]. Do not reuse the previous target from an older template.", [2])],
          ["You locate and paste the current hold policy.", "The meeting's changed turnaround is not supplied.", "You reconcile the service directory yourself."],
          ["Graph grounding across the policy and directory", "Meeting recall surfaces the unapproved turnaround", "Word integration for a reviewed template"],
          "Review with Student Records, then place the approved wording in the Word template."),
        scenario(2, "Respond to a family records request", "Draft a careful process response without confirming a student's enrollment.",
          "Draft a response to a family member asking for attendance and grades. Explain the institution's authorization-check process and a next step without confirming enrollment, disclosing records, or deciding whether a FERPA exception applies.", 160, ["FERPA", "consent", "records"],
          [source("Records Disclosure Procedure", "Registrar SharePoint", "Staff must verify identity, scope, and the basis for disclosure before any education-record release. Uncertain requests go to the privacy office."),
           source("Consent Workflow Guide", "Student Records SharePoint", "A submitted consent form is not proof that its scope covers a particular request. Authorized staff validate scope and status in the approved system."),
           source("Family Inquiry Template Review", "Registrar Teams recap", "The approved opening is neutral and must not confirm whether an individual is enrolled. Portal routing language is approved; response-time language remains under review.")],
          [output("Thank you for reaching out", "We can explain the process for requesting records, but this response does not confirm anyone's enrollment."),
           output("Authorization comes first", "Before any disclosure, the university must apply its authorization procedures. The applicable form and verification channel are [TO CONFIRM]."),
           output("Next step", "Please use the approved records-request process [TO CONFIRM]. Staff will review the request; receipt of a form does not guarantee release.")],
          [output("Thank you for reaching out", "We can explain our request process. This reply does not confirm whether any individual is enrolled.", [3]),
           output("Authorization comes first", "Authorized staff must verify identity, disclosure basis, and consent scope and status. Submitting a form does not itself authorize the requested release.", [1, 2]),
           output("Next step", "Use the authenticated records-request portal. Staff will route uncertain requests to the privacy office. Response timing remains [TO CONFIRM]; no records are included in this reply.", [1, 3])],
          ["You supply both disclosure and consent procedures.", "Chat cannot infer your institution's authorization workflow.", "An older template may contain an unapproved response time."],
          ["Permission-aware retrieval of approved procedures", "Source comparison flags template limitations", "Word drafting with a human disclosure review"],
          "Privacy staff review the draft; verify authorization outside the chat before any release."),
        scenario(3, "Reconcile census reporting changes", "Explain aggregate reporting variances without mistaking a definition change for enrollment loss.",
          "Prepare a census variance brief from aggregate counts. Separate real changes from reporting-definition changes; show the denominator and arithmetic. Do not sum overlapping categories or imply causal explanations. End with two validation questions.", 240, ["census", "enrollment", "Excel", "reporting"],
          [source("Census Aggregate Workbook", "Institutional Research SharePoint", "Synthetic example: prior reported total 10,000; current reported total 9,800. Current total excludes 150 visiting students who would have been counted under the prior definition."),
           source("Census Definition Register", "Registrar SharePoint", "Visiting students are excluded from the new reporting total. Full-time and undergraduate categories overlap and cannot be added together."),
           source("Census Sign-off Recap", "Institutional Research Teams meeting", "Institutional Research must validate a like-for-like bridge before publication. The final prior-year recast is not yet approved.")],
          [output("Observed change", "Reported totals and the reference population are [TO CONFIRM]. A percentage cannot be calculated without both counts."),
           output("Comparability", "Check whether census definitions changed before describing a decline. Overlapping enrollment categories must not be added."),
           output("Validation questions", "Has the prior period been recast? Which office signs off on the reporting definition [TO CONFIRM]?")],
          [output("Reported movement", "The synthetic reported change is 9,800 − 10,000 = −200, or −2.0% using 10,000 as the denominator.", [1]),
           output("Like-for-like bridge", "Adding the 150 excluded visiting students gives a provisional prior-definition current total of 9,950: −50, or −0.5%. This is a bridge, not an approved recast; overlapping categories are not summed.", [1, 2]),
           output("Before publication", "Has Institutional Research approved the bridge? Is the prior-year recast final [TO CONFIRM]? The recap requires sign-off; it does not establish a cause for the change.", [3])],
          ["You export an approved aggregate workbook first.", "The definition register is not independently available in this baseline.", "You find the sign-off meeting note separately."],
          ["Analyst with approved aggregate data; availability varies", "Graph grounding connects definitions and sign-off", "Excel integration for reviewing the variance bridge"],
          "Validate formulas and denominator in Excel; obtain Institutional Research approval.")
      ]
    },
    {
      id: "provost", name: "Provost's Office / Academic Affairs", shortName: "Academic Affairs", icon: "AA",
      description: "Bring policy, committee decisions, and academic planning into the same brief.",
      prompts: [
        scenario(1, "Brief a policy decision", "Separate adopted enrollment policy from a cabinet proposal still under discussion.",
          "Write a provost decision brief on the proposed late-add exception. Separate current policy, cabinet recommendations, unresolved questions, and the decision needed. Do not present a discussion or a draft as an adopted rule.", 230, ["enrollment", "cabinet", "policy"],
          [source("Enrollment Exception Policy", "Provost SharePoint", "The published rule routes late-add exceptions through the registrar and academic dean. No standing department-level delegation is in the current policy."),
           source("Tuesday Cabinet Recap", "Academic Affairs Teams", "Cabinet discussed department-level delegation for limited cases but requested a risk assessment before a vote. No decision was recorded."),
           source("Late-add Consultation Note", "Academic Affairs SharePoint", "Registrar requested an audit trail and an appeal route. The implementation owner and effective term have not been assigned.")],
          [output("Current policy", "The authorized approval path is [TO CONFIRM]. A summary cannot establish the current rule without the published policy."),
           output("Discussion, not decision", "Any meeting proposal should be labeled as a recommendation until an authorized decision is supplied."),
           output("Decision needed", "Confirm the approval authority, effective term, implementation owner, and unresolved risks before announcing a change.")],
          [output("Current rule", "Late-add exceptions still route through the registrar and academic dean. The published policy does not delegate approval to departments.", [1]),
           output("Cabinet position", "Department-level delegation was discussed, not adopted. Cabinet requested a risk assessment before a vote.", [2]),
           output("Decision needed", "Resolve the registrar's audit-trail and appeal concerns, then assign an implementation owner and effective term [TO CONFIRM]. Do not announce a policy change yet.", [3])],
          ["You locate the published policy rather than a draft.", "Tuesday's cabinet discussion must be pasted or supplied.", "You manually compare consultation notes against the recap."],
          ["Graph grounding across policy and consultation", "Meeting recall distinguishes discussion from approval", "Word integration for the decision brief"],
          "Insert the reviewed brief in Word; route the decision through university governance."),
        scenario(2, "Check a curriculum proposal", "Identify missing evidence before a new program reaches the academic committee.",
          "Produce a curriculum-review readiness checklist for a proposed certificate. Cover learning outcomes, assessment, resource commitments, and approval dependencies. Distinguish present evidence from missing evidence; do not predict accreditation approval.", 250, ["curriculum", "accreditation", "assessment"],
          [source("Certificate Proposal Draft", "Academic Affairs SharePoint", "The synthetic proposal includes three learning outcomes and a curriculum map. Assessment milestones are present, but the scoring rubric is not attached."),
           source("Program Approval Checklist", "Provost SharePoint", "Committee review requires an assessment rubric, library consultation, and a signed resource statement. External notification needs a separate determination."),
           source("Curriculum Committee Recap", "Academic Affairs Teams", "The library consultation is complete. Resource sign-off was deferred. No determination about external notification was recorded.")],
          [output("Evidence to gather", "Collect the proposal, assessment materials, library consultation, and the institution's approval checklist."),
           output("Readiness", "The status of each requirement is [TO CONFIRM] until the supporting materials are supplied."),
           output("Boundary", "Committee readiness is not accreditation approval. Confirm external notification requirements with the responsible office.")],
          [output("Present", "The draft contains outcomes, a curriculum map, and assessment milestones. The committee recap confirms completed library consultation.", [1, 3]),
           output("Not ready", "The scoring rubric is missing and the signed resource statement is deferred. Both are required for review; do not mark the packet complete.", [1, 2, 3]),
           output("Separate determination", "External notification remains [TO CONFIRM]. Assign that question to the accreditation liaison rather than treating internal review as an external approval.", [2, 3])],
          ["You assemble the proposal and current checklist.", "The baseline has no independent committee-meeting recall.", "An attachment gap is easy to miss across separate files."],
          ["Cross-document grounding checks evidence against criteria", "Teams meeting context updates readiness", "Researcher can organize the evidence; verify availability"],
          "Committee staff verify the checklist and source versions before circulating the packet."),
        scenario(3, "Reconcile instructional capacity", "Put workload assumptions next to the actual planning numbers.",
          "Draft an instructional-capacity note using aggregate sections and teaching capacity. Calculate the gap, distinguish planned from committed capacity, and list dependencies. Do not recommend individual workload assignments or assume hiring approval.", 210, ["workload", "budget", "Excel"],
          [source("Teaching Capacity Workbook", "Academic Planning SharePoint", "Synthetic plan: 120 required sections, 108 committed sections of capacity, and 8 additional sections conditional on approved appointments."),
           source("Workload Planning Principles", "Provost SharePoint", "Only approved appointments count as committed capacity. Workload changes require local consultation; aggregate planning is not an individual assignment."),
           source("Budget Planning Recap", "Provost Teams meeting", "The 8 conditional sections are not funded yet. Finance requested a contingency for the remaining capacity gap.")],
          [output("Capacity position", "Required sections minus committed capacity gives the current gap. Both inputs are [TO CONFIRM]."),
           output("Conditional capacity", "Keep proposed appointments separate from approved capacity. Do not treat a planning discussion as hiring authorization."),
           output("Next decision", "Confirm funding status and consultation requirements before allocating workload.")],
          [output("Committed gap", "120 required sections − 108 committed = a 12-section gap in this synthetic plan.", [1]),
           output("Conditional case", "If all 8 conditional sections are approved, the remaining gap is 4. They are not yet funded and must not be counted as committed capacity.", [1, 2, 3]),
           output("Decision needed", "Finance needs a contingency for the remaining gap. Confirm funding and local consultation [TO CONFIRM]; this note assigns no individual workload.", [2, 3])],
          ["You provide the aggregate planning workbook.", "Appointment status is held in a separate meeting recap.", "Policy assumptions must be assembled by hand."],
          ["Excel integration for explicit scenario arithmetic", "Graph grounding connects workload and budget context", "Meeting recall preserves conditional decisions"],
          "Review the two capacity cases in Excel and obtain academic and finance sign-off.")
      ]
    },
    {
      id: "research-admin", name: "Research Administration & Sponsored Programs", shortName: "Research Admin", icon: "RA",
      description: "From scattered award documents to a source-backed next step. No compliance shortcuts.",
      prompts: [
        scenario(1, "Check proposal readiness", "Reconcile a sponsor checklist, internal routing rules, and the last handoff meeting.",
          "Prepare a proposal-readiness brief for NIH/NSF submissions. Group findings as ready, blocked, or awaiting verification; give the responsible office and next action. Distinguish sponsor requirements from university routing rules. Never invent a deadline or certify compliance.", 260, ["grants", "NIH", "NSF", "proposal", "compliance"],
          [source("Sponsor Submission Checklist", "Sponsored Programs SharePoint", "Fictional training checklist: the NIH packet's facilities narrative is present; the NSF packet's current-pending support confirmation is absent. Sponsor instructions and applicability must be checked against the current solicitation; this checklist is not authoritative guidance."),
           source("Proposal Routing Policy", "Research Office SharePoint", "Internal routing requires a budget review and department approval before institutional submission. The internal target is separate from the sponsor deadline; neither date is supplied in this example."),
           source("Tuesday Proposal Handoff", "Sponsored Programs Teams recap", "Budget review is complete. Department approval is pending. Sponsored Programs must confirm the current support-document requirements against the applicable solicitation; no sponsor deadline was confirmed.")],
          [output("Start with the requirements", "For each proposal, confirm the applicable solicitation, required attachments, and current sponsor instructions. Sponsor and internal dates are [TO CONFIRM]."),
           output("Check institutional routing", "Collect the budget-review result and department approval. Their status cannot be inferred from the task description."),
           output("Before submission", "Ask Sponsored Programs to verify outstanding requirements and the responsible office. This generic checklist does not establish submission readiness.")],
          [output("Ready · budget review", "The handoff records completed budget review; the training checklist includes the NIH facilities narrative. Neither fact establishes overall sponsor compliance.", [1, 3]),
           output("Blocked · department approval", "Department approval remains pending and is required by the internal routing policy. Next action: the department confirms approval to Sponsored Programs.", [2, 3]),
           output("Verify · support documents and dates", "The NSF support confirmation is absent. Sponsored Programs must check the applicable solicitation, not rely on the training checklist. Sponsor deadline and internal target: [TO CONFIRM].", [1, 2, 3])],
          ["You find and paste the sponsor checklist and routing policy.", "Last week's handoff is invisible until you supply it.", "You reconcile missing approvals across three sources."],
          ["Graph grounding connects SharePoint evidence", "Teams meeting recall supplies the latest handoff", "Researcher can structure the source review; availability varies"],
          "Human review first. Move the verified readiness brief into the Word routing packet."),
        scenario(2, "Review effort-reporting exceptions", "Explain aggregate exceptions without certifying effort or inventing a sponsor rule.",
          "Write an effort-reporting exception triage brief from aggregate counts. Separate timing issues from allocation questions, state the evidence needed, and route each category to the responsible office. Do not treat payroll as proof of effort or certify any report.", 240, ["effort", "grants", "NIH", "NSF", "compliance"],
          [source("Effort Exception Summary", "Research Finance SharePoint", "Synthetic aggregate: 12 open exceptions, consisting of 7 late-review cases and 5 allocation questions. No individual records or salary data are included."),
           source("Effort Review Procedure", "Sponsored Programs SharePoint", "Late reviews route to the departmental effort coordinator. Allocation questions require Research Finance review of supporting activity evidence. Payroll distribution alone does not establish effort."),
           source("Effort Close Meeting", "Research Finance Teams recap", "A blanket extension was discussed but not approved. Research Finance requested the underlying activity evidence for allocation questions. No revised due date was adopted.")],
          [output("Triage categories", "Separate late review from questions about allocation. Counts and category definitions are [TO CONFIRM]."),
           output("Evidence needed", "Collect the approved procedure and supporting activity evidence; payroll distribution alone cannot establish effort."),
           output("Routing", "Confirm the responsible offices and any approved extension. This draft is not effort certification.")],
          [output("Timing · 7 cases", "Route the 7 late-review exceptions to the departmental effort coordinator. The synthetic counts reconcile: 7 + 5 = 12.", [1, 2]),
           output("Allocation · 5 cases", "Research Finance needs supporting activity evidence for the 5 allocation questions. Payroll distribution alone is not sufficient evidence of effort.", [1, 2, 3]),
           output("No blanket extension", "The meeting discussed an extension but did not approve it. Revised due date: [TO CONFIRM]. Authorized reviewers retain all certification decisions.", [3])],
          ["You supply the aggregate exception export.", "The review procedure is not retrieved in this baseline.", "You must locate whether the extension was actually approved."],
          ["Graph grounding joins counts to routing rules", "Meeting recall distinguishes a proposal from approval", "Excel integration supports count reconciliation"],
          "Review aggregate totals in Excel; authorized staff resolve and certify in the approved system."),
        scenario(3, "Prepare an award closeout brief", "Expose reconciliation gaps before a financial closeout is signed.",
          "Prepare a closeout reconciliation brief from aggregate award figures. Show the provisional balance, identify unresolved commitments and deliverables, and assign next actions by office. Distinguish financial reconciliation from sponsor acceptance; do not approve a final report.", 250, ["award", "closeout", "grants", "Excel"],
          [source("Award Closeout Workbook", "Research Finance SharePoint", "Synthetic aggregate award: authorized budget $500,000; posted expenditure $462,000; open commitments $18,000. Pending adjustments are not quantified."),
           source("Closeout Requirements Register", "Sponsored Programs SharePoint", "Closeout requires verified final expenditures and applicable financial and technical deliverables. Due dates must be taken from the award terms; no date is provided in this training register."),
           source("Closeout Handoff Recap", "Sponsored Programs Teams", "Procurement must check open commitments for release or payment. Research Finance has not finalized pending adjustments. Technical-report acceptance is not documented.")],
          [output("Reconcile the balance", "Subtract posted expenditure and valid commitments from the authorized budget. The amounts and pending adjustments are [TO CONFIRM]."),
           output("Check deliverables", "Use the award terms to verify required financial and technical reports and their due dates."),
           output("Keep the boundary clear", "An apparent unspent balance does not establish closeout readiness or sponsor acceptance.")],
          [output("Provisional balance", "$500,000 − $462,000 − $18,000 = $20,000 before pending adjustments. This synthetic figure is not an approved final balance.", [1]),
           output("Resolve commitments", "Procurement must verify release or payment of the $18,000 commitments. Research Finance must quantify pending adjustments before final reconciliation.", [1, 3]),
           output("Deliverables remain open", "Technical-report acceptance is not documented. Sponsored Programs must check award-term due dates [TO CONFIRM] and required deliverables; no final report is approved here.", [2, 3])],
          ["You assemble an approved financial export and award terms.", "The baseline cannot independently retrieve the handoff recap.", "Spreadsheet arithmetic alone misses deliverable status."],
          ["Analyst can examine approved aggregates; verify availability", "Graph grounding connects requirements to financial context", "Teams recall highlights unresolved commitments"],
          "Reconcile the workbook and award terms; finance and Sponsored Programs approve separately.")
      ]
    },
    {
      id: "student-affairs", name: "Student Affairs / Dean of Students", shortName: "Student Affairs", icon: "SA",
      description: "Careful campus communications and service planning, without individual case data.",
      prompts: [
        scenario(1, "Draft a service disruption update", "Keep a campus message aligned to confirmed operations, not rumor.",
          "Draft a campus-facing update about a temporary student-service relocation. State confirmed service changes, an accessible alternative, and the next update. Do not speculate about cause, promise a reopening date, or mention individual cases.", 180, ["communications", "accessibility", "services"],
          [source("Service Continuity Bulletin", "Student Affairs SharePoint", "The student-service desk is temporarily operating remotely. Essential appointments remain available; walk-in service at the usual location is paused."),
           source("Accessible Service Channels", "Student Support SharePoint", "Students can request a phone appointment or an accessible online appointment through the authenticated service portal. No individual contact details are supplied here."),
           source("Service Continuity Check-in", "Dean of Students Teams recap", "Facilities has not confirmed a reopening date. The next operational review is scheduled, but public update timing is awaiting communications approval.")],
          [output("Service update", "A temporary service change is in effect [TO CONFIRM]. Confirm which appointments and locations are affected before publication."),
           output("How to reach support", "Use the approved alternative access route [TO CONFIRM]; provide an accessible option."),
           output("What happens next", "Reopening and update timing are [TO CONFIRM]. Do not infer safety conditions or causes from incomplete notes.")],
          [output("Service update", "The student-service desk is temporarily remote. Essential appointments remain available; walk-in service at the usual location is paused.", [1]),
           output("Access support", "Use the authenticated service portal to request a phone or accessible online appointment.", [2]),
           output("Next update", "Facilities has not confirmed a reopening date. Public update timing is [TO CONFIRM] pending communications approval; no cause is asserted.", [3])],
          ["You find and paste the approved service bulletin.", "Accessible alternatives live in another source.", "The latest reopening discussion must be supplied."],
          ["Graph grounding uses approved service channels", "Meeting recall prevents an invented reopening promise", "Word integration for communications review"],
          "Communications and accessibility staff approve the wording before publication."),
        scenario(2, "Review aggregate support demand", "Compare service demand and appointment capacity without profiling students.",
          "Write a support-capacity brief using aggregate requests and available slots. Calculate the planning gap, distinguish requests from unique students, and propose two operational questions. Do not diagnose need, rank individual risk, or assert that every request requires a slot.", 220, ["wellbeing", "capacity", "Excel"],
          [source("Support Demand Workbook", "Student Affairs SharePoint", "Synthetic weekly counts: 180 appointment requests and 150 available slots. Requests can include duplicates; unique-student counts are not available."),
           source("Support Metrics Dictionary", "Student Support SharePoint", "Requests are contacts, not unique students or confirmed clinical need. Not every contact requires an appointment; counts are for operational planning only."),
           source("Service Capacity Review", "Student Affairs Teams recap", "The team requested deduplication and a check of unfilled slots before considering extended hours. No staffing expansion was approved.")],
          [output("Demand signal", "Collect aggregate requests and available capacity for the same period. Counts are [TO CONFIRM]."),
           output("Interpret with care", "Request volume may include duplicates and is not a measure of unique students or clinical need."),
           output("Operational questions", "Can requests be deduplicated? Are existing slots being used before additional hours are considered?")],
          [output("Planning difference", "180 requests − 150 slots = 30 more requests than available slots in the synthetic week. This is not a 30-student unmet-need estimate.", [1, 2]),
           output("Definition limits", "Requests may repeat and may not require appointments. Unique-student counts and a like-for-like demand measure remain [TO CONFIRM].", [1, 2]),
           output("Before extending hours", "Can the team deduplicate requests and verify unfilled slots? The review requested those checks and did not approve expanded staffing.", [3])],
          ["You export and de-identify service aggregates.", "The metrics dictionary must be supplied explicitly.", "The baseline does not independently know the staffing discussion."],
          ["Excel integration preserves arithmetic and definitions", "Graph grounding joins the metrics dictionary", "Teams context separates questions from decisions"],
          "Service leads validate definitions and capacity; no individual support decisions are automated."),
        scenario(3, "Prepare an emergency-aid process FAQ", "Reconcile eligibility guidance with the committee's still-pending changes.",
          "Draft an emergency-aid process FAQ covering how to apply, how review works, timing, and appeals. Use only approved policy for eligibility statements. Do not promise funding, infer eligibility, or include applicant information.", 230, ["emergency aid", "policy", "FAQ"],
          [source("Emergency Aid Guidance", "Dean of Students SharePoint", "Applications use the authenticated aid portal. Review is case-specific and subject to available funds; an application does not guarantee an award."),
           source("Aid Review Procedure", "Student Affairs SharePoint", "The aid team checks completeness before committee review. Applicants may request reconsideration through the portal; no fixed turnaround is specified."),
           source("Aid Committee Recap", "Dean of Students Teams", "The committee discussed simplifying evidence requirements but deferred the change for policy review. Existing requirements remain in force.")],
          [output("How do I apply?", "Use the institution's approved application route [TO CONFIRM]. Submitting an application does not guarantee funding."),
           output("How does review work?", "Eligibility, evidence requirements, and the review sequence must be checked against current approved policy."),
           output("When will I hear back?", "Timing and the reconsideration route are [TO CONFIRM]. This FAQ cannot decide an individual request.")],
          [output("How do I apply?", "Use the authenticated aid portal. Review is case-specific and subject to available funds; no award is guaranteed.", [1]),
           output("What happens next?", "The aid team checks completeness before committee review. Proposed simplified evidence requirements were deferred; current requirements still apply.", [2, 3]),
           output("Timing and reconsideration", "A fixed turnaround is not specified [TO CONFIRM]. Reconsideration requests go through the portal; the FAQ makes no individual eligibility decision.", [2])],
          ["You paste approved guidance, not a committee draft.", "The review procedure is a separate source to find.", "You must check whether the proposed change passed."],
          ["Graph grounding reconciles policy and procedure", "Meeting recall identifies a deferred change", "Word integration for an approved accessible FAQ"],
          "Aid and policy owners approve the FAQ; keep case-specific review in the authorized system.")
      ]
    },
    {
      id: "university-it", name: "University IT / CIO Office", shortName: "University IT", icon: "IT",
      description: "Make the rollout measurable, permission-aware, and operationally supportable.",
      prompts: [
        scenario(1, "Triage oversharing before a pilot", "Prioritize aggregate permission findings before licensing a cohort.",
          "Draft a pre-pilot access-remediation brief from an aggregate permissions review. Prioritize broad sharing and ownerless sites, name responsible teams, and define evidence for closure. Do not enumerate sensitive files, change access, or imply Copilot bypasses permissions.", 240, ["permissions", "SharePoint", "security", "pilot"],
          [source("Pilot Access Review Summary", "CIO SharePoint", "Synthetic findings across the proposed pilot scope: 6 sites have broad organization-wide links; 2 lack a confirmed owner. The categories may overlap."),
           source("Information Access Standard", "IT Governance SharePoint", "Site owners must validate audience and remove unnecessary broad links. Ownerless sites require a steward before pilot inclusion. Changes require the normal approval process."),
           source("Copilot Pilot Risk Review", "CIO Teams recap", "The pilot scope excludes unresolved ownerless sites. Security requested evidence of link review before opening access to the cohort. No bulk permission changes were authorized.")],
          [output("Prioritize review", "Identify broadly shared resources and sites without accountable owners. Counts and scope are [TO CONFIRM]."),
           output("Remediate through owners", "Ask site owners and security to validate access. Do not make blanket permission changes from a generated summary."),
           output("Close the finding", "Keep approved change records and evidence of review. Copilot respects permissions but does not repair oversharing.")],
          [output("First priority", "Review the 6 sites with broad links; confirm stewards for the 2 ownerless sites. Do not total them as 8 unique sites because categories may overlap.", [1]),
           output("Pilot boundary", "Exclude unresolved ownerless sites. Site owners validate intended audiences and process any link changes through normal approvals.", [2, 3]),
           output("Closure evidence", "Security needs documented link review and confirmed ownership. No bulk changes are authorized; unresolved scope remains [TO CONFIRM].", [2, 3])],
          ["You supply a safe aggregate permissions report.", "The access standard must be located separately.", "Risk-review decisions are not automatically recalled here."],
          ["Graph grounding connects findings and controls", "Teams recall preserves the approved pilot boundary", "Word integration for the risk register"],
          "Security and site owners approve remediation; this demo never inspects or changes permissions."),
        scenario(2, "Reconcile service-review actions", "Turn an incident trend and review meeting into an honest CIO update.",
          "Prepare a service-review brief from aggregate ticket trends. Show the rate change with its denominator, separate observed symptoms from verified root causes, and list approved actions versus proposals. Do not claim an SLA breach without its defined measure.", 220, ["service desk", "incident", "Teams"],
          [source("Service Desk Aggregate Dashboard", "IT Operations SharePoint", "Synthetic comparison: access-related tickets rose from 80 to 100 across equal four-week periods. Total ticket volume and SLA measurements are not provided."),
           source("Service Measurement Standard", "IT Governance SharePoint", "Ticket counts alone do not establish an SLA breach. Root causes require incident review evidence, and comparisons must use like periods."),
           source("Monthly Service Review", "IT Operations Teams recap", "Refreshing the access FAQ was approved. An identity-platform change was proposed but not approved. The incident review has not confirmed a shared root cause.")],
          [output("Trend", "Compare equal periods and calculate change from the prior period. Counts and denominators are [TO CONFIRM]."),
           output("Interpretation", "A higher ticket count does not by itself establish a root cause or an SLA breach."),
           output("Actions", "Separate approved fixes from proposed changes and confirm the accountable service owner.")],
          [output("Observed trend", "Access tickets increased by 20: (100 − 80) / 80 = 25% across equal synthetic four-week periods. Share of all tickets is unknown.", [1]),
           output("No causal leap", "The incident review has not confirmed a shared root cause. SLA performance is [TO CONFIRM]; ticket counts alone are not the defined measure.", [2, 3]),
           output("Approved vs proposed", "Proceed with the approved access-FAQ refresh. The identity-platform change is only a proposal and needs the normal decision process.", [3])],
          ["You extract the dashboard numbers yourself.", "The measurement standard is not in the baseline context.", "You paste the meeting to distinguish proposals from actions."],
          ["Graph grounding joins metrics and service definitions", "Teams meeting recall finds recorded decisions", "Word integration for a source-backed CIO brief"],
          "Service owners verify incident evidence, then publish the reviewed operations brief."),
        scenario(3, "Evaluate the Copilot pilot", "Compare end-to-end time without counting checking effort as saved time.",
          "Write a pilot-evaluation note using matched aggregate task timings. Include review time, calculate net time recovered, and separate adoption from time savings. State limitations and a scale/refine/stop recommendation conditional on governance and quality gates.", 250, ["ROI", "adoption", "pilot", "Analyst"],
          [source("Pilot Measurement Workbook", "CIO SharePoint", "Synthetic matched-task medians: baseline 50 minutes including review; assisted preparation 25 minutes plus 10 minutes review, for 35 minutes total. Weekly active participants: 8 of 12."),
           source("Pilot Success Rubric", "IT Governance SharePoint", "Scale requires at least 20% lower median end-to-end task time, no quality regression, and no unresolved high-risk data incident. Gates are institution-defined pilot goals."),
           source("Pilot Retrospective", "CIO Teams recap", "Reviewers requested a larger matched sample. Quality review is not complete; no final security sign-off is recorded. Participants asked for more champion office hours.")],
          [output("Measure end to end", "Collect comparable task timings including retrieval, review, and rework. Baseline and assisted totals are [TO CONFIRM]."),
           output("Keep adoption separate", "Weekly use does not prove time savings. Use a defined denominator and evaluate quality as well as speed."),
           output("Decision", "Do not scale on anecdotal speed alone; confirm quality and governance gates first.")],
          [output("Observed recovery", "50 − (25 + 10) = 15 minutes recovered per matched task, or 30%. Omitting review would overstate recovery as 50%. These are synthetic medians, not a causal study.", [1]),
           output("Adoption and quality", "8 / 12 participants were active, about 67%. The time goal is met in this sample, but quality review and security sign-off are incomplete.", [1, 2, 3]),
           output("Recommendation · refine", "Collect a larger matched sample and offer champion office hours. Scale only after quality and security gates are verified [TO CONFIRM].", [2, 3])],
          ["You gather matched timings and include review time.", "The success rubric is not available unless supplied.", "Retrospective caveats need a separate export."],
          ["Analyst can explore the workbook; verify availability", "Graph grounding applies the institution's rubric", "Teams recall keeps unresolved quality gates visible"],
          "Finance validates capacity value; the steering group makes the scale / refine / stop decision.")
      ]
    },
    {
      id: "advancement", name: "Advancement & Alumni Relations", shortName: "Advancement", icon: "AD",
      description: "Stewardship and campaign reporting grounded in restrictions, not assumptions.",
      prompts: [
        scenario(1, "Draft a fund stewardship update", "Tie an aggregate impact update to the actual gift restrictions.",
          "Draft an aggregate scholarship-fund stewardship update. Distinguish awarded from disbursed amounts, explain permitted uses, and flag missing impact evidence. Do not identify recipients, quote donors, promise outcomes, or imply a restriction can be waived.", 210, ["stewardship", "gift restrictions", "scholarships"],
          [source("Scholarship Fund Summary", "Advancement SharePoint", "Synthetic annual totals: $120,000 awarded and $90,000 disbursed. The $30,000 difference is scheduled for a later disbursement cycle; recipient data is excluded."),
           source("Fund Restriction Abstract", "Gift Administration SharePoint", "The example fund supports undergraduate tuition assistance. General operating expenses and unapproved program costs are outside the summarized restriction."),
           source("Stewardship Planning Recap", "Advancement Teams", "Only aggregate financial figures are cleared for this draft. Retention and completion impact evidence is not yet validated; no recipient stories are approved.")],
          [output("Support provided", "Report aggregate awarded and disbursed amounts separately. Verified totals are [TO CONFIRM]."),
           output("Purpose", "Use the approved gift-restriction language [TO CONFIRM]; do not imply flexibility that has not been authorized."),
           output("Impact", "Avoid retention or completion claims without validated evidence. No recipient story is included.")],
          [output("Financial update", "The synthetic fund awarded $120,000, of which $90,000 was disbursed. The remaining $30,000 is scheduled for a later cycle; it is not additional spending.", [1]),
           output("Restricted purpose", "Support is for undergraduate tuition assistance. The abstract does not authorize general operating or unapproved program expenses.", [2]),
           output("Impact still to verify", "Only aggregate figures are cleared. Retention and completion effects remain [TO CONFIRM]; no recipient stories or outcome promises appear in this draft.", [3])],
          ["You export cleared aggregate fund figures.", "Chat does not independently retrieve gift restrictions here.", "You find which impact claims have been approved."],
          ["Graph grounding connects the restriction abstract", "Meeting recall limits claims to cleared evidence", "Word integration for the stewardship draft"],
          "Gift administration verifies restrictions; stewardship staff approve the final Word update."),
        scenario(2, "Reconcile campaign reporting", "Keep commitments, receipts, and goal progress from becoming one misleading number.",
          "Prepare a campaign dashboard narrative from aggregate figures. Separate new commitments from cash received, use the published goal definition, and show the progress calculation. Do not sum overlapping amounts or imply receipts are unrestricted funds.", 220, ["campaign", "pledges", "Excel"],
          [source("Campaign Aggregate Workbook", "Advancement SharePoint", "Synthetic campaign-to-date qualified commitments total $8 million against a $10 million commitment goal. Cash received is $3 million and is already associated with commitments; it is not additive."),
           source("Campaign Counting Guide", "Gift Administration SharePoint", "The goal is measured using qualified commitments, not cash receipts. Commitment recognition and cash availability differ. Gift restrictions continue to apply."),
           source("Campaign Reporting Review", "Advancement Teams recap", "The committee requested separate commitments and receipts in the board narrative. A revised forecast has not been approved.")],
          [output("Progress measure", "Confirm the campaign's counting convention, goal, and qualified totals before calculating progress."),
           output("Cash is different", "Report receipts separately from commitments. Adding them may double count the same gifts."),
           output("Outlook", "Forecast and restriction status are [TO CONFIRM]. The narrative should not infer spending availability.")],
          [output("Goal progress", "$8 million / $10 million = 80% of the synthetic commitment goal, with a $2 million commitment gap.", [1, 2]),
           output("Receipts shown separately", "$3 million in cash receipts is associated with commitments and must not be added to the $8 million. Receipt does not remove gift restrictions.", [1, 2]),
           output("Forecast boundary", "The committee requested separate measures. A revised forecast is not approved [TO CONFIRM]; this update does not predict goal completion.", [3])],
          ["You extract safe campaign aggregates from the CRM.", "The goal-counting definition must be supplied.", "The baseline does not see the board-reporting review."],
          ["Excel integration exposes the denominator", "Graph grounding applies the counting guide", "Teams recall preserves forecast approval status"],
          "Reconcile to the authorized gift system, then obtain gift-administration sign-off."),
        scenario(3, "Plan an alumni event follow-up", "Translate aggregate feedback into actions while respecting communication preferences.",
          "Create a follow-up action brief for an alumni event using aggregate feedback. Separate operational improvements from outreach proposals; identify consent and accessibility checks. Do not profile attendees, infer giving capacity, or generate a recipient list.", 210, ["alumni", "consent", "events", "accessibility"],
          [source("Alumni Event Feedback Summary", "Alumni Relations SharePoint", "Synthetic feedback themes: clearer captioning instructions and more remote participation options. Counts and representativeness are not supplied."),
           source("Alumni Communications Standard", "Advancement SharePoint", "Outreach must honor channel preferences and opt-outs in the authorized system. Event participation is not consent to fundraising contact."),
           source("Alumni Event Debrief", "Alumni Relations Teams", "Updating captioning instructions was approved. A hybrid follow-up event is a proposal awaiting budget review. No new fundraising outreach was approved.")],
          [output("Operational improvements", "Review aggregate feedback for actionable service issues; prevalence and representativeness are [TO CONFIRM]."),
           output("Outreach boundary", "Check communication preferences in the authorized system. Attendance alone does not authorize fundraising contact."),
           output("Next steps", "Separate approved improvements from proposals requiring budget or consent review.")],
          [output("Approved improvement", "Update captioning instructions, a feedback theme with approval in the debrief. Frequency and representativeness remain [TO CONFIRM].", [1, 3]),
           output("Proposal, not commitment", "Remote participation options inform a proposed hybrid follow-up event. Budget review is pending; do not announce it as scheduled.", [1, 3]),
           output("Respect preferences", "Check channel preferences and opt-outs in the authorized system before any outreach. Event participation does not establish fundraising consent, and no new solicitation was approved.", [2, 3])],
          ["You supply de-identified event feedback.", "Communication standards need to be located and pasted.", "You must check the debrief before treating an idea as approved."],
          ["Graph grounding connects feedback and consent rules", "Meeting recall identifies approved improvements", "Word / Teams integration for a reviewed action brief"],
          "Alumni staff review accessibility and preferences; send only through the approved workflow.")
      ]
    }
  ];
})();
